version: '1'

services:
  client:
    restart: unless-stopped
    image: portfolio:production
    build: 
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - 80:80
