version: '1'

services:
  frontend:
    restart: unless-stopped
    image: portfolio-frontend:production
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile.production
    ports:
      - 80:80
  backend:
    restart: unless-stopped
    image: portfolio-backend:production
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.production
    ports:
      - 8000:8000
