version: "3.8"
services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: portfolio-frontend:development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - portfolio-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: portfolio-backend:development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=db_havilash_sivaratnam"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - portfolio-network

  # MySQL service
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db_havilash_sivaratnam
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - portfolio-network

# Volumes
volumes:
  db_data:

# Networks
networks:
  portfolio-network:
