version: '1'

services:
  frontend:
    restart: unless-stopped
    image: portfolio:development
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    # volumes:  
    # - ./frontend:/app
