name: Build and copy files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set CI environment variable
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Install all dependencies
        run: npm install
        working-directory: havilash_sivaratnam/frontend

      - name: Build
        run: npm run build
        working-directory: havilash_sivaratnam/frontend

      - name: Create dist directory
        run: |
          mkdir dist
          cp -r havilash_sivaratnam/frontend/build/* dist/
          mkdir -p dist/subdomains/backend/
          cp -r havilash_sivaratnam/backend/* dist/subdomains/backend/

      - name: Push dist directory to dist branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
