name: Build and copy files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies and build frontend
        run: |
          cd havilash_sivaratnam/frontend/
          npm ci
          npm run build
      - name: Copy files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout dist || git checkout --orphan dist
          git checkout main -- havilash_sivaratnam/frontend/build/*
          mkdir -p subdomains/backend/
          git checkout main -- havilash_sivaratnam/backend/*
          mv havilash_sivaratnam/backend/* subdomains/backend/
          rm -rf havilash_sivaratnam/
          git add .
          git commit -m "Build and copy files"
          git push origin dist
